[package]
name = "ran_git"
version = "0.1.0"
authors = ["Loïc Pelleau <loicpelleau@yahoo.fr>"]

[dependencies]
hyper = "^0.10"
url = "^1.5"
serde_derive = "^1.0"
serde = "^1.0"
serde_json = "^1.0"
rand = "^0.3"
